### ISSUE TITLE
adblock.dat 无法引用

### ISSUE THREAD

**Issue by 328902301** [REIJI007/AdBlock_Rule_For_V2ray#1]
添加引用后，引用方式没错，报错如下：

Failed to start: main: failed to load config files: [config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: ext:adblock.dat:adblock > infra/conf: failed to load external sites: adblock from adblock.dat > infra/conf: list not found in adblock.dat: ADBLOCK

使用了 https://github.com/MetaCubeX/geo 这个项目的工具导出 adblock 标签的目录，确实可以导出数据。但是 xray 中的确无法引用，不知问题在哪。

**Comment by 328902301** [comment]
已经通过下面项目链接教程以及本仓库提供的 adblock.txt 自建构建解决。
https://github.com/v2fly/domain-list-community?tab=readme-ov-file#generate-dlcdat-manually

**Comment by 328902301** [comment]
哦哦，原来如此，只用了 xray 测试。该广告拦截太多了，误杀也有些，拿来测试玩玩，真的用的话会有一些卡顿感。😅

**Comment by REIJI007** [comment]
爬取的上游可以自己添加，我这边一百多个上游肯定是有些误杀的，条目数量多，移动设备吃太多内存肯定卡
